# Generated by Django 2.2.7 on 2019-11-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('full_name_override', models.CharField(blank=True, max_length=100)),
                ('hometown', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('recipe_yield', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('procedure', models.TextField()),
                ('baker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Baker')),
            ],
        ),
    ]
