# Generated by Django 2.2.7 on 2019-11-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='baker',
        ),
        migrations.AddField(
            model_name='recipe',
            name='baker',
            field=models.ManyToManyField(to='recipes.Baker'),
        ),
    ]
