# Generated by Django 2.2.7 on 2019-11-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipephoto_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephoto',
            name='cutline',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BakerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bakers')),
                ('cutline', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=2)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
    ]
