# Generated by Django 2.2.7 on 2019-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20191106_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(blank=True),
        ),
    ]
