# Generated by Django 2.2.7 on 2019-11-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20191106_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baker',
            name='notes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='backer_bio_notes',
            field=models.TextField(blank=True),
        ),
    ]
