# Generated by Django 2.2.7 on 2019-11-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20191106_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='backer_bio_notes',
            new_name='baker_bio_notes',
        ),
    ]
