# Generated by Django 2.2.7 on 2019-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20191106_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cookie_type',
            field=models.CharField(blank=True, choices=[('Ro', 'Rolled'), ('B', 'Bar'), ('D', 'Drop'), ('Rf', 'Refrigerator')], max_length=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='features',
            field=models.ManyToManyField(to='recipes.RecipeFeature'),
        ),
    ]
