# Generated by Django 2.2.7 on 2019-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipefeature_sort_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
